chomsky_phrases = [
    "All over the place, from the popular culture to the propaganda system, there is constant pressure to make people feel that they are helpless, that the only role they can have is to ratify decisions and to consume.",
    "Any dictator would admire the uniformity and obedience of the U.S. media.",
    "As soon as questions of will or decision or reason or choice of action arise, human science is at a loss.",
    "Censorship is never over for those who have experienced it. It is a brand on the imagination that affects the individual who has suffered it, forever.",
    "Colorless green ideas sleep furiously.",
    "Education must provide the opportunities for self-fulfillment; it can at best provide a rich and challenging environment for the individual to explore, in his own way.",
    "Either you repeat the same conventional doctrines everybody is saying, or else you say something true, and it will sound like it's from Neptune.",
    "Everybody's worried about stopping terrorism. Well, there's a really easy way: stop participating in it.",
    "I have often thought that if a rational Fascist dictatorship were to exist, then it would choose the American system.",
    "If the Nuremberg laws were applied, then every post-war American president would have been hanged.",
    "If we choose, we can live in a world of comforting illusion.",
    "If we don't believe in freedom of expression for people we despise, we don't believe in it at all.",
    "In this possibly terminal phase of human existence, democracy and freedom are more than just ideals to be valued - they may be essential to survival.",
    "Language is a process of free creation; its laws and principles are fixed, but the manner in which the principles of generation are used is free and infinitely varied. Even the interpretation and use of words involves a process of free creation.",
    "Personally, I'm in favor of democracy, which means that the central institutions of society have to be under popular control. Now, under capitalism, we can't have democracy by definition. Capitalism is a system in which the central institutions of society are in principle under autocratic control.",
    "Propaganda is to a democracy what the bludgeon is to a totalitarian state.",
    "Resistance is feasible even for those who are not heroes by nature, and it is an obligation, I believe, for those who fear the consequences and detest the reality of the attempt to impose American hegemony.",
    "Sports plays a societal role in engendering jingoist and chauvinist attitudes. They're designed to organize a community to be committed to their gladiators.",
    "States are not moral agents, people are, and can impose moral standards on powerful institutions.",
    "The Bible is one of the most genocidal books in history.",
    "The intellectual tradition is one of servility to power, and if I didn't betray it I'd be ashamed of myself.",
    "The more you can increase fear of drugs and crime, welfare mothers, immigrants and aliens, the more you control all the people.",
    "The only justification for repressive institutions is material and cultural deficit. But such institutions, at certain stages of history, perpetuate and produce such a deficit, and even threaten human survival.",
    "The principle that human nature, in its psychological aspects, is nothing more than a product of history and given social relations removes all barriers to coercion and manipulation by the powerful.",
    "The United States is unusual among the industrial democracies in the rigidity of the system of ideological control - 'indoctrination,' we might say - exercised through the mass media.",
    "To some degree it matters who's in office, but it matters more how much pressure they're under from the public.",
    "Unlimited economic growth has the marvelous quality of stilling discontent while maintaining privilege, a fact that has not gone unnoticed among liberal economists.",
    "We can, for example, be fairly confident that either there will be a world without war or there won't be a world - at least, a world inhabited by creatures other than bacteria and beetles, with some scattering of others.",
    "You never need an argument against the use of violence, you need an argument for it.",
]
chomsky_triggers = {
    'max': ['Mr. Headroom is my master now...'],
    'headroom': ['And I thought Rupurt Murdoch controlled the media...'],
    'towel': ["Have a towel.", 'drop', 'a towel'],
    'basement': ["The basement is easy enough to find. Just go to the Janitor's Closet, which is east of the Main Hall."],
    'bomb': ["Christian Slater left some dynamite under the toilet..."],
    'christian': ["I'm an atheist, myself."],
    'slater': ["What a polite young man. He gave me this.", 'drop', 'a gun'],
}
hooks_phrases = [
    "Death is with you all the time; you get deeper in it as you move towards it, but it's not unfamiliar to you. It's always been there, so what becomes unfamiliar to you when you pass away from the moment is really life.",
    "For me, forgiveness and compassion are always linked: how do we hold people accountable for wrongdoing and yet at the same time remain in touch with their humanity enough to believe in their capacity to be transformed?",
    "I always tell my students that Malcolm X came both to his spirituality and to his consciousness as a thinker when he had solitude to read. Unfortunately, tragically, like so many young black males, that solitude only came in prison.",
    "I began writing a book on love because I felt that the United States is moving away from love.",
    "I feel like there is always something trying to pull us back into sleep, that there is this sort of seductive quality in all the hedonistic pleasures that pull on us.",
    "I have been thinking about the notion of perfect love as being without fear, and what that means for us in a world that's becoming increasingly xenophobic, tortured by fundamentalism and nationalism.",
    "I often find it easier to be teaching or giving to others, and often struggle with the place of my own pleasure and joy.",
    "I thought about how we need to make children feel that there are times in their lives when they need to be alone and quiet and to be able to accept their aloneness.",
    "I will not have my life narrowed down. I will not bow down to somebody else's whim or to someone else's ignorance.",
    "I'm so disturbed when my women students behave as though they can only read women, or black students behave as though they can only read blacks, or white students behave as though they can only identify with a white writer.",
    "I'm such a girl for the living room. I really like to stay in my nest and not move. I travel in my mind, and that's a rigorous state of journeying for me. My body isn't that interested in moving from place to place.",
    "I've never given up on the mystical dimensions of Christianity. I always laugh at myself because in the morning I sit zazen, but then I always take time to say my Christian prayers at the same time.",
    "It's in the act of having to do things that you don't want to that you learn something about moving past the self. Past the ego.",
    "Many spiritual teachers - in Buddhism, in Islam - have talked about first-hand experience of the world as an important part of the path to wisdom, to enlightenment.",
    "Some people act as though art that is for a mass audience is not good art, and I think this has been a very negative thing. I know that I have wanted very much to write books that are accessible to the widest audience possible.",
    "We judge on the basis of what somebody looks like, skin color, whether we think they're beautiful or not. That space on the Internet allows you to converse with somebody with none of those things involved.",
    "When we drop fear, we can draw nearer to people, we can draw nearer to the earth, we can draw nearer to all the heavenly creatures that surround us.",
    "Yesterday I was thinking about the whole idea of genius and creative people, and the notion that if you create some magical art, somehow that exempts you from having to pay attention to the small things.",
]
hooks_triggers = {
    'max': ["Max Headroom took over this building. He's holding court upstairs."],
    'headroom': ["Max Headroom has infected the entire network. Only an EMP could stop him now."],
    'emp': ["How do you make an EMP? Well, I suppose you could blow up the city power grid..."],
    'power': ["The city power grid is in the basement, but it's guarded by Winona Ryder. She's fierce."],
    'basement': ["I don't get out much."],
    'winona': ['Watch out for her.'],
    'ryder': ["She'll steal your wallet."],
    'book': ['What about scrolls?', 'drop', 'a fireball scroll'],
    'read': ['Have some reading material', 'drop', 'a fireball scroll'],
    'library': ['The Media Studies Library is well stocked', 'drop', 'a fireball scroll'],
}
max_phrases = [
    "Ah -- love -- the walks over soft grass, the smiles over candlelight, the fights over just about everything else....",
    "How can you tell a network executive is lying? His lips move!",
    "Say, would someone mind checking the ratings? I seem to have an audience of two.",
    "And I love, love, l-l-love... love those blip-blip-blip-blipverts!",
    "Freedom. You know, writers have no freedom on TV. One rude suggestion, and the censors are straight on their back. Not on their back in a rude way.",
    "Now, I'm no librarian, in fact, I don't know what star sign I am. But, as a famous person once said, 'You can fool some of the people some of the time, but you can't fool all of the people all of the time.' And as I - another more famous person - once said, 'If you don't teach them to read, you can fool them whenever you like.'",
    "Have you any idea how successful censorship is on TV? Don't know the answer? Hmm. Successful, isn't it?",
    "Well, most people would agree that censors are a silly breed. In fact, it surprises me how they ever manage to breed at all.",
    "As, 'tis Max Headroom here, and I quote from the bard, Shakespeare, a writer: 'The quality of TV is not strained, it dropeth as the gentle ratings dropeth to a very tiny percentage share and, lo, 'tis gone.' Of course, Shakespeare would have loved your rating system. Twelfth Night would have been lucky to have lasted *one*!",
    "Y'know... I get the feeling there's a lot of faces out there... watching... me! And I can tell you it brings a lump to my ratings. Yes, this is Network 23. The net-net-net-net-network that puts it right... where they want you to be!",
    "Yes, t-t-t-t-tune into Network 23! The network that's a *real* mind-blower!",
]
max_triggers = {
    'map': ["Here you go, sport!", 'drop', 'a map'],
    'evil': ["Evil? Me?"],
    'noam': ["He has the s-spirit of a true revolutionary!"],
    'chomsky': ["Last time I heard, he was handing out t-t-towels in the bathroom!"],
    'bell': ["She's the media studies librarian."],
    'hooks': ["She has some very interesting books."],
}
bots = [
    {
        'name': 'Noam Chomsky',
        'description': ' is muttering about secret military documents.',
        'location': "the men's room",
        'phrases': chomsky_phrases,
        'greeting': 'Would you care for a towel?',
        'triggers': chomsky_triggers,
        'attack': 30,
        'defense': 20, #+15 trousers
        'hp': 40,
    },
    {
        'name': 'Bell Hooks',
        'description': "'s name tag reads: 'bell hooks.'",
        'location': 'the media studies library',
        'phrases': hooks_phrases,
        'greeting': 'Welcome to the media studies library.',
        'triggers': hooks_triggers,
        'attack': 20, #+15 pen
        'defense': 30,
        'hp': 40,
    },
    {
        'name': 'Winona Ryder',
        'description': " eyes your shoes greedily.",
        'location': 'the basement',
        'greeting': 'Go Westerberg High!',
        'aggressive': 2,
        'attack': 20, #+5 heels
        'defense': 20, #+5 dress
        'hp': 30,
    },
    {
        'name': 'Max Headroom',
        'description': "'s enormous, rubbery face is projected on the wall.",
        'location': 'the classroom',
        'phrases': max_phrases,
        'greeting': "Welcome t-t-t-t-to my Media Studies building! Although you are t-t-technically my prisoner, please make yourself at home - feel free to explore your c-c-cage! Type 'commands' whenever you need a little help, and chat with the locals. You'll have plenty of time to get to know each other. We can be a little confusing at first, but we react well to the right kind of conversation, if you catch my meaning. For instance, see what I know about a map of the b-building!",
        'triggers': max_triggers,
        'attack': 50,
        'defense': 50,
        'hp': 50,
    },
    {
        'name': 'a minor problematic',
        'description': " doesn't bother you much.",
        'mobile': 3,
        'aggressive': 4,
        'hp': 15
    },
    {
        'name': 'a problematic',
        'description': " is somewhat troubling.",
        'mobile': 4,
        'aggressive': 10,
        'defense': 10
    },
    {
        'name': 'a glaring problematic',
        'description': " is downright embarrassing.",
        'mobile': 5,
        'aggressive': 11,
        'attack': 10
    },
    {
        'name': 'the Pyrrhonian Problematic',
        'description': " makes you insecure.",
        'mobile': 10,
        'aggressive': 5,
        'attack': 12,
        'defense': 12,
        'hp': 20,
    },
    {
        'name': 'the Media Studies Dragon',
        'description': ' attacks you!',
        'location': 'the media studies secret room',
        'greeting': 'You dare disturb me!',
        'aggressive': 1,
        'attack': 20,
        'defense': 20,
        'hp': 25,
    }
]