#types: shoes, pants, shirt, cape, shield, weapon, key, lock, food, spell, map
#unique: shoes, pants, shirt, cape, shield, weapon
items = [
    {
        'name': 'a towel',
        'description': ' can be worn as a cape',
        'location': "noam chomsky",
        'type': 'cape',
        'defense': 5,
    },
    {
        'name': 'a toilet plunger',
        'description': " sucks",
        'location': "the janitor's closet",
        'verb': ' plunges ',
        'attack': 5,
    },
    {
        'name': 'a bomb',
        'description': ' looks ready to go off',
        'location': 'a filthy stall',
        'type': 'key',
        'special': 'the power grid',
    },
    {
        'name': 'the power grid',
        'description': ' is mad with power',
        'location': 'the basement',
        'type': 'lock',
        'special': ["destroyed the Media Studies building, ending Max Headroom's reign of terror once and for all. There are no survivors.", 'game over'],
        'take': False,
    },
    {
        'name': 'a small key',
        'description': ' smells awful',
        'location': 'the urinal',
        'type': 'key',
        'special': 'an S&M shrine',
    },
    {
        'name': 'an S&M shrine',
        'description': ' dominates the room',
        'location': 'the media studies dungeon',
        'type': 'lock',
        'special': ["The shrine opens up, revealing a secret passage to the north.", 'door', ['north', 'the media studies secret room']],
        'take': False,
    },
    {
        'name': 'the Media Studies shield',
        'description': " gives new meaning to 'Consumer Protection'",
        'location': 'the media studies secret room',
        'type': 'shield',
        'defense': 15,
    },
    {
        'name': 'the whip',
        'description': " is the kinkiest thing you've seen all day",
        'location': 'the media studies dungeon',
        'verb': ' whips ',
        'attack': 10,
    },
    {
        'name': 'Marxist trousers',
        'description': ': for the workers of the world, by the workers of the world',
        'location': 'noam chomsky',
        'type': 'pants',
        'defense': 15,
    },
    {
        'name': "Bell Hooks's pen",
        'description': ' is mighty, indeed',
        'location': 'bell hooks',
        'verb': ' stabs ',
        'attack': 15,
    },
    {
        'name': "spiked combat heels",
        'description': ' look sharp',
        'location': 'winona ryder',
        'type': 'shoes',
        'attack': 5,
    },
    {
        'name': "a cute blouse",
        'description': ' looks sharp',
        'location': 'winona ryder',
        'type': 'shirt',
        'defense': 5,
    },
    {
        'name': 'a small cracker',
        'description': ' is calling your name',
        'location': 'a minor problematic',
        'type': 'food',
        'special': ['You feel better', 'hp', 15],
    },
    {
        'name': 'a loaf of bread',
        'description': ' makes your mouth water',
        'location': 'a problematic',
        'type': 'food',
        'special': ['You feel much better', 'hp', 35],
    },
    {
        'name': 'a red apple',
        'description': ' glows',
        'location': 'a glaring problematic',
        'type': 'food',
        'special': ['You feel stronger!', 'attack', 10],
    },
    {
        'name': 'a green apple',
        'description': ' glows',
        'location': 'the pyrrhonian problematic',
        'type': 'food',
        'special': ['You feel stronger!', 'defense', 10],
    },
    {
        'name': 'a fireball scroll',
        'description': ' looks boring',
        'location': 'bell hooks',
        'type': 'spell',
        'special': [' throws a fireball at ', 'hp', -20],
        'charge': 1,
    },
    {
        'name': 'a gun',
        'description': ' makes you nervous',
        'location': 'noam chomsky',
        'type': 'spell',
        'special': [' fires a gun at ', 'hp', -10],
        'charge': 6,
    },
    {
        'name': 'a piece of meat',
        'description': ' feels like a piece of meat',
        'location': 'the kitchen',
        'type': 'food',
        'special': ['You feel great!', 'hp', 25],
    },
    {
        'name': 'a map',
        'description': ' catches your eye',
        'location': 'max headroom',
        'type': 'map',
        'special': "<br>second floor:<br>---------<br>|.......|<br>|.......|<br>|..C....|<br>|.......|<br>---------<br><br>first floor:<br>---------<br>|.......|<br>|..K.L..|<br>|..M.J..|<br>|F.R.U..|<br>---------<br><br>basement:<br>---------<br>|......S|<br>|......D|<br>|......B|<br>|.......|<br>---------<br>",
    },
    {
        'name': 'a sign',
        'description': ' claims to list all bot triggers',
        'location': 'the lobby',
        'type': 'map',
        'special': "<br>/=============\<br>|Noam Chomsky:|<br>|~ max . . . .|<br>|~ headroom. .|<br>|~ towel . . .|<br>|~ basement. .|<br>|~ bomb. . . .|<br>|~ christian .|<br>|~ slater. . .|<br>|-------------|<br>|Bell Hooks: .|<br>|~ max . . . .|<br>|~ headroom. .|<br>|~ emp . . . .|<br>|~ power . . .|<br>|~ basement. .|<br>|~ winona. . .|<br>|~ ryder . . .|<br>|~ book. . . .|<br>|~ read. . . .|<br>|~ library . .|<br>|-------------|<br>|Max Headroom:|<br>|~ map . . . .|<br>|~ evil. . . .|<br>|~ noam. . . .|<br>|~ chomsky . .|<br>|~ bell. . . .|<br>|~ hooks . . .|<br>\=============/",
        'take': False,
    },
]